# Generated by Django 5.2 on 2025-04-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='materials/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='association',
            field=models.TextField(blank=True, null=True, verbose_name='Association (ex: Carpe, CI, ...)'),
        ),
        migrations.AlterField(
            model_name='location',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='location',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_end',
            field=models.DateTimeField(verbose_name='Fin de location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_start',
            field=models.DateTimeField(verbose_name='Début de location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Numéro de téléphone'),
        ),
    ]
