# Generated by Django 5.2 on 2025-04-19 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouvertureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom du type de couverture')),
            ],
        ),
        migrations.CreateModel(
            name='Couverture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('organizer', models.CharField(max_length=200, verbose_name="Nom de l'organisateur")),
                ('event_name', models.CharField(max_length=200, verbose_name="Nom de l'événement")),
                ('place_name', models.CharField(max_length=200, verbose_name='Lieu')),
                ('date', models.DateField(verbose_name='Date')),
                ('duration_comments', models.TextField(verbose_name='Commentaires sur la durée')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numéro de téléphone')),
                ('specific_comments', models.TextField(blank=True, null=True, verbose_name='Commentaires spécifiques')),
                ('couverture_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couverture.couverturetype', verbose_name='Type de couverture')),
            ],
        ),
    ]
