# Generated by Django 5.2 on 2025-04-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpestudentem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('link', models.URLField()),
            ],
        ),
    ]
