# Generated by Django 5.2 on 2025-04-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpestudentem', '0002_contentbutton'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectspresentation',
            name='image',
        ),
        migrations.AddField(
            model_name='projectspresentation',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
