# Generated by Django 5.2 on 2025-04-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpestudentem', '0003_remove_projectspresentation_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentbutton',
            name='link',
            field=models.CharField(max_length=255),
        ),
    ]
